name: Docker Builder
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Docker-build:
    runs-on: ubuntu-22.04
    name: Build Docker Image
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set Up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Harbor
        run: echo "${{ secrets.HARBOR_PASSWORD }}" | docker login ${{ secrets.HARBOR_REGISTRY }} -u ${{ secrets.HARBOR_USERNAME }} --password-stdin

      - name: Build Image and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: |
            linux/amd64
          push: true
          build-args: |
            COMMIT_TAG=${{ github.sha }}
            DEFAULT_PORT_PRODUCTTION=81
            DEFAULT_PORT_HTTP=555
            DEFAULT_PORT_HTTPS=666
          tags: |
            ${{ secrets.HARBOR_REGISTRY }}/${{ secrets.HARBOR_USERNAME }}/nginx-proxy-manager-with-other-ports:latest
